### ISSUE TITLE
Routines support

### ISSUE THREAD

**Issue by klonwar** [humbertogontijo/python-roborock#102]
Is it possible and planned to add routines support? At least trigger existing one, created inside application

![photo_2023-08-02_12-43-43](https://github.com/humbertogontijo/python-roborock/assets/12374932/8de5006e-11f2-4453-bc5c-4492174fdf87)

![photo_2023-08-02_12-44-37](https://github.com/humbertogontijo/python-roborock/assets/12374932/9a1ac365-086e-4a7e-9f60-b2cd05190588)

**Comment by Lash-L** [comment]
See https://github.com/humbertogontijo/homeassistant-roborock/issues/419

**Comment by klonwar** [comment]
Ok, thank you for the answer, I'll close the issue then

**Comment by arne182** [comment]
I use an automation
![Screenshot_20230803_090704_Home Assistant](https://github.com/humbertogontijo/python-roborock/assets/844102/93587c53-8d2b-4972-bae9-47d52d631d84)
And a helper button to start the automation
![Screenshot_20230803_090826_Home Assistant](https://github.com/humbertogontijo/python-roborock/assets/844102/8113a36c-5910-4bb3-ac75-b2e7fe8a135e)

**Comment by h4nnes** [comment]
Hi @arne182,
how do you get the segment id? 
Thx!
