### ISSUE TITLE
CLI command get_status return nothing

### ISSUE THREAD

**Issue by Jezza34000** [humbertogontijo/python-roborock#111]
Hi !
I recently acquired a Roborock Q REVO and I'm looking for assistance regarding some missing information or commands in the Home Assistant component.
When I attempt to query my vacuum, I don't receive any response:

```
5820T:~/HomeAssistant$ roborock command --device_id *************** --cmd get_status
INFO:roborock.cloud_api:[Withee] Connecting to mqtt
INFO:roborock.cloud_api:[Withee] Starting mqtt loop
INFO:roborock.cloud_api:[Withee] Connected to mqtt mqtt-eu-5.roborock.com:8883
INFO:roborock.cloud_api:[Withee] Subscribed to topic rr/m/o/*****************/*********/******************
INFO:roborock.cloud_api:[Withee] Disconnecting from mqtt
```

What might I be doing wrong? Is there something that's missing?

**Comment by pangolingo** [comment]
For posterity: I learned that I needed to pass the debug flag `-d to be able to see the output of the command (the mqtt response):

```
roborock -d command --device_id *************** --cmd get_status
```

**Comment by Jezza34000** [comment]
Thank you for help ! It work :-) I didn't find the solution i was Send_command directly in HomeAssistant
