### ISSUE TITLE
Missing Error codes for dock water tanks

### ISSUE THREAD

**Issue by ThomDyson** [humbertogontijo/python-roborock#112]
For the S7 MaxV Ultra, cleaning the mop can cause two errors not currently handled. For both errors, the code may mean the tank is missing, empty, or has some other issue.

38 - Clean water tank error. 
39 - Dirty water tank error.

**Comment by arne182** [comment]
https://github.com/humbertogontijo/python-roborock/blob/main/roborock/code_mappings.py#L225

**Comment by ThomDyson** [comment]
Not sure how I missed that. Thanks.
