### ISSUE TITLE
API to switch map?

### ISSUE THREAD

**Issue by LaUr3nTiU** [humbertogontijo/python-roborock#162]
Not a defect, but since there's no section to discuss, I'm asking this here.

I've looked over the API commands, and I didn't see anything that would instruct the vacuum to switch the map. I have 2 maps saved (one for each floor), and I'l like the vacuum to use 1 map or the other when cleaning, but not sure how to do that. Thanks!

**Comment by Lash-L** [comment]
you need to u se the command load_multi_map
