### ISSUE TITLE
ModuleNotFoundError: No module named 'imp'

### ISSUE THREAD

**Issue by hidrissi-hass** [humbertogontijo/python-roborock#191]
Hi,

Python 3.12 is dropping the 'imp' module.
There is a way to avoid using it ?
Thx

Hicham

**Comment by hidrissi-hass** [comment]
`'imp'` module was used in `'construct'` module 'till `2.10.56`
could you please use at least `2.10.57` of `'construct'` module ?

**Comment by Lash-L** [comment]
This was fixed in https://github.com/humbertogontijo/python-roborock/releases/tag/v0.39.2
