### ISSUE TITLE
How to set Vacuum only mode?

### ISSUE THREAD

**Issue by derekakelly** [humbertogontijo/python-roborock#193]
I used the instructions to setup an automation to clean a single room. I've looked through all of the documentation, but I am unsure how to make it only vacuum and not mop.  Here's the yaml so far:

> service: vacuum.send_command
> target:
>   entity_id: vacuum.roborock_s8_pro_ultra
> data:
>   command: app_segment_clean
>   params:
>     - segments:
>         - 16
>       repeat: 1

**Comment by multinet33** [comment]
Hello, Do you find a solution ? looking for the same function thanks.

**Comment by freakyjoe8** [comment]
I achieve this by setting set_mop_mode = fast + mop_intensity = off. 

I'm doing this via home assistant where the mop_intensity option is available via UI though I haven't found it in the docs of python-roborock. But looking into the code there seems to be an option for this: https://github.com/humbertogontijo/python-roborock/blob/4f44d03f1691aef03af451f0e2733749c212a315/roborock/code_mappings.py#L295 

Maybe that helps

**Comment by derekakelly** [comment]
@freakyjoe8 I can confirm that worked for me. I found the option in Home Assistant and setup it up like this. I didn't change the mode mode and it worked.
<img width="733" alt="image" src="https://github.com/humbertogontijo/python-roborock/assets/5824837/22d33863-70ab-459d-98ea-a801833b01bc">
