### ISSUE TITLE
Pip command not found

### ISSUE THREAD

**Issue by itsaustinjordan** [humbertogontijo/python-roborock#196]
I am trying to update this in hopes it will fix the issue of the HACS roborock failing to initialize. It was working before but seems like the update messed it up. When I run 

`pip install python-roborock`

I get

`pip: command not found`

Any help appreciated

**Comment by Lash-L** [comment]
That's an issue with your instance, you have to install pip. Unfortunately if you ask this question, I would recommend not doing it. Manipulating things in your container inside HA is a dangerous road to go down and you can mess up your system.

If you really want to do it, you actually need to exec into the docker container that runs Home assistant, not just the home assistant ssh.

I would recommend switching to the core addon.
