### ISSUE TITLE
Add support for Roborock S8 MaxV Ultra

### ISSUE THREAD

**Issue by user-08-151** [humbertogontijo/python-roborock#201]
Please add support for Roborock S8 MaxV Ultra which identifies in Home Assistant as 'roborock.vacuum.a97'.

There seems to be some new codes that are currently not defined and set to some defaults:
```
2024-05-02 12:14:49.564 WARNING (MainThread) [roborock.code_mappings] Missing RoborockFanSpeedS7MaxV code: 110 - defaulting to 105
2024-05-02 12:14:49.564 WARNING (MainThread) [roborock.code_mappings] Missing RoborockMopIntensityS7 code: 209 - defaulting to 200
2024-05-02 12:14:49.565 WARNING (MainThread) [roborock.code_mappings] Missing RoborockDockTypeCode code: 10 - defaulting to 'unknown'
2024-05-02 12:14:49.565 WARNING (MainThread) [roborock.code_mappings] Missing RoborockMopModeS7 code: 306 - defaulting to 300
```

**Comment by Lash-L** [comment]
@Wolf6660 tagging you here as you had a similar request.

Here are the commands I got from reverse engineering the latest code with the s8 maxv ultra.

```
app_start_patrol
app_resume_patrol
app_start_pet_patrol
app_set_cross_carpet_cleaning_status
set_clean_repeat_times
app_set_dirty_replenish_clean_status
set_stretch_tag_status
get_stretch_tag_status
set_right_brush_stretch_status
get_right_brush_stretch_status
set_dirty_object_detect_status
get_dirty_object_detect_status
set_wash_water_temperature
get_wash_water_temperature
app_empty_rinse_tank_water
set_pet_supplies_deep_clean_status
get_pet_supplies_deep_clean_status
set_ap_mic_led_status
get_ap_mic_led_status
set_handle_leak_water_status
get_handle_leak_water_status
app_ignore_dirty_objects
matter.get_status
matter.dnld_key
matter.reset
set_gap_deep_clean_status
get_gap_deep_clean_status
app_set_robot_setting
app_get_robot_setting

```

Can you try a handful of these commands and ensure that they are functional for you?

In Home assistant Developper tools -> Services -> VAcuum: Send Command. Select your vacuum as the entity, and the strings as the commands.

Some may not work as you need parameters with them

Is there anything from these that you are still looking for?

I have a much older vacuum - so I have no means of testing this Some things may just exist in the code but not in reality.

As well can you send me all of the options (in your app) for fan speed, and mop options?

**Comment by Lash-L** [comment]
> I found following definitions within the Android app (assets/plugins/home_card/robot.vacuum.cleaner.zip -> index.android.bundle) which seems to be the codes for code_mappings.py:


Can you send me that bundle - the bundle I downloaded using the api doesn't seem to contain the lines you are referencing

**Comment by AirborneEagle** [comment]
We need to add the s8 Maxv Ultra to supported devices now, yes?
