### ISSUE TITLE
Get Map Qrevo (Master)

### ISSUE THREAD

**Issue by Neuroquila-n8fall** [humbertogontijo/python-roborock#221]
Obviously something has changed in the protocol and map retrieval does not work with this model.

How can I help getting this updated? I already set up packet capture and looked into it but I have no idea what could be of interest (but I assume it's the MQTT comms)

**Comment by Lash-L** [comment]
I haven't heard anyone else having this problem, can you please walk me through what you are doing?

**Comment by Neuroquila-n8fall** [comment]
Now this is funny... today it started working out of nowhere. No firmware update or something in between... I can't even find a difference in network traffic from yesterday to today.
