### ISSUE TITLE
Api timeout doesn't seem to recover

### ISSUE THREAD

**Issue by Lash-L** [humbertogontijo/python-roborock#31]
When I was originally testing and the prefix was wrong for setting the fan, it would give me a timeout error every 4 seconds. I'm not sure if that was just because the command was wrong or if there was something else going on. If you have any ideas/ want to test as well, that would probably be good.

I thought about adding a timeout limit in the socket controller. If it times out three times in a row, then it will disconnect and reconnect. Not sure if that actually would fix the problem though. Wanted to hear your opinion.

**Comment by humbertogontijo** [comment]
If the command is wrong (prefix included) the robot will never respond back that it was wrong. Resulting the timeout

**Comment by Lash-L** [comment]
Yeah, but right now I'm not sure if we are able to recover. Message gets sent - we get the timeout, but we continue to get the timeout, rather than when we get the timeout, we keep waiting for the response. At least that is what it seemed like to me

**Comment by humbertogontijo** [comment]
Yes, the socket expects sequential commands. Once a command is sent wrong, the socket needs to be closed. Maybe we should disconnect after a timeout.
