### ISSUE TITLE
Vacuum status reported as an int rather than being mapped to a string

### ISSUE THREAD

**Issue by cryptk** [humbertogontijo/python-roborock#52]
Until yesterday, I had string based vacuum statuses in Home Assistant, now I have int statuses.  I believe this is because the model string for my S8 Pro Ultra is incorrect in the library.

this line https://github.com/humbertogontijo/python-roborock/blob/main/roborock/const.py#L33 should be `roborock.vacuum.a70` for the new S8 Pro Ultra

**Comment by cryptk** [comment]
@Lash-L can we re-open this one? My PR did fix the log line about not having data for my particular robot, but I am still getting my status reported as an int rather than as a string even with the latest main commit of the HASS integration, which should be using 0.13.1 of this library (my fix went out in 0.12.1)

**Comment by Lash-L** [comment]
Sounds good.

I'll take a look at it probably tomorrow unless @humbertogontijo has a chance.

**Comment by cryptk** [comment]
I might take another whack at poking around for the cause as well

**Comment by Lash-L** [comment]
It looks like Humberto is also actively working on the package library -so he may already be dealing with it

**Comment by humbertogontijo** [comment]
Yes. I'll fix it soon

**Comment by humbertogontijo** [comment]
status should be string now

**Comment by cryptk** [comment]
Just tested, all good now! Thanks!
