### ISSUE TITLE
Please provide an example of using app_segment_clean

### ISSUE THREAD

**Issue by Chrischi-** [humbertogontijo/python-roborock#61]
Could you please provide an example of using app_segment_clean?

I get an error every time. No matter which syntax I use.

For Example
```
roborock -d command --device_id xyxyxyxyxyxyxyxyxyx --cmd app_segment_clean --params "[23]"

DEBUG:roborock.cloud_api:id=79354 Requesting method app_segment_clean with [23]
roborock.exceptions.VacuumError: (-10005, 'Param is not an array')
```

```
roborock -d command --device_id xyxyxyxyxyxyxyxyxyx --cmd app_segment_clean --params '[{"segments":[23],"repeat":2}]'

DEBUG:roborock.cloud_api:id=40826 Requesting method app_segment_clean with [{"segments":[23],"repeat":2}]
roborock.exceptions.VacuumError: (-10005, 'Param is not an array')
```

My room mapping looks like this:
```
DEBUG:roborock.cloud_api:id=75853 Response from get_room_mapping: [[16, '12105189'], [18, '12105192'], [19, '12105181'], [20, '12105179'], [21, '12105183'], [22, '12105185'], [23, '12105177'], [24, '12105187']]
```

And how could I do local commands without the cloud_api?

Thanks in advance for your time
@Lash-L @humbertogontijo

**Comment by Chrischi-** [comment]
@Lash-L
@humbertogontijo

I really don't want to bother anyone with this, but can someone help me with this?

I would hate to set up HA to see how the requests are made.

**Comment by Lash-L** [comment]
I've never really used our cli - but I tried it to get you a good answer.

There was a bug that I fixed in #66 When that goes lives you should be able to do it.

**Comment by Chrischi-** [comment]
Thank you for the answer and the quick fix. 

But I don't think it will work like that. 
Not all commands use additional param(eter)s

**Comment by Lash-L** [comment]
Why would this not work then?

**Comment by Chrischi-** [comment]
Because `json.loads(params)` expects a value and this is `none` for commands without `--params`

**Comment by Lash-L** [comment]
changed

**Comment by Chrischi-** [comment]
That works. Thanks
