### ISSUE TITLE
Command to start/stop Empty the bin?

### ISSUE THREAD

**Issue by mgriffin13** [humbertogontijo/python-roborock#85]
Is there a command that would allow me to engage the auto-empty? Since I schedule the vacuum during DND period, I need to run an empty bin cycle, but the app doesn't allow me to schedule that, so I'm looking to use HA instead.

**Comment by Lash-L** [comment]
command is 
```app_start_collect_dust```

**Comment by mgriffin13** [comment]
Thank you. I was browsing the issues on your HACS integration and just found this. I guess I should have done more research  :)

https://github.com/humbertogontijo/homeassistant-roborock/issues/130#issuecomment-1417988489
